### ISSUE TITLE
How to use flag --netrc (.netrc authentication data) of youtube-dl

### ISSUE THREAD

**Issue by krswin** [hyeonsangjeon/youtube-dl-nas#25]
I want to set Authentication data for youtube login to download private videos.
How to use flag --netrc (.netrc authentication data) of youtube-dl?

Please help. thanks.

**Comment by hyeonsangjeon** [comment]
The current image supports this through a mounted netrc file plus `YTDLP_EXTRA_ARGS`. Example:

```yaml
volumes:
  - /volume1/docker/youtube-dl-nas/netrc:/config/netrc:ro
environment:
  YTDLP_EXTRA_ARGS: --netrc --netrc-location /config/netrc
```

Keep the file readable only by the intended NAS user and use the standard netrc format. These arguments are passed to both metadata lookup and downloads. Closing this as completed.
